# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: 'server/BrekkenScan.Api'
        arguments: '--configuration Production --output published-server'
        zipAfterPublish: false
        modifyOutputPath: false
      displayName: 'dotnet publish'

    - task: CopyFiles@2
      inputs:
        SourceFolder: 'published-server'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
      displayName: 'copy published server to artifact staging'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'www'
        publishLocation: 'pipeline'
      displayName: 'publish artifact as www'

- stage: Release
  displayName: 'Release to Production'
  jobs:
  - deployment: Release
    environment: Production
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              artifactName: 'www'
              targetPath: '$(System.DefaultWorkingDirectory)'

          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Brekkenscanner - Azure'
              appType: 'webAppLinux'
              WebAppName: 'brekkenscanner-staging'
              packageForLinux: '$(System.DefaultWorkingDirectory)'
              StartupCommand: 'dotnet BrekkenScan.Api.dll'